name = "immeubleassur-com"
account_id = "fcca12a7ddf64e6dc782494bdb487b8e"
compatibility_date = "2026-07-19"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "immeubleassur-db"
database_id = "TO_REPLACE_WITH_CLOUDFLARE_D1_DATABASE_ID"


