name = "immeubleassur-com"
compatibility_date = "2026-07-19"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "immeubleassur-db"
database_id = "50aec73e-fec7-4233-9801-4825006091fa"



