PRAGMA foreign_keys = ON;
INSERT INTO editorial_sources (id, name, url, source_type, category, authority, crawl_policy, active, payload, created_at, updated_at) VALUES ('service-public-particuliers', 'Service-Public.fr particuliers', 'https://www.service-public.fr/abonnements/rss/actu-actualites-particuliers.rss', 'rss', 'droit-logement', 'official', 'rss-summary-only', 1, '{"id":"service-public-particuliers","name":"Service-Public.fr particuliers","url":"https://www.service-public.fr/abonnements/rss/actu-actualites-particuliers.rss","source_type":"rss","category":"droit-logement","authority":"official","crawl_policy":"rss-summary-only"}', '2026-07-28T00:36:01.362Z', '2026-07-28T00:36:01.362Z') ON CONFLICT(id) DO UPDATE SET name = excluded.name, url = excluded.url, source_type = excluded.source_type, category = excluded.category, authority = excluded.authority, crawl_policy = excluded.crawl_policy, active = 1, payload = excluded.payload, updated_at = excluded.updated_at;
INSERT INTO editorial_sources (id, name, url, source_type, category, authority, crawl_policy, active, payload, created_at, updated_at) VALUES ('service-public-professionnels', 'Service-Public.fr professionnels', 'https://www.service-public.fr/abonnements/rss/actu-actualites-professionnels.rss', 'rss', 'entreprises-immobilier', 'official', 'rss-summary-only', 1, '{"id":"service-public-professionnels","name":"Service-Public.fr professionnels","url":"https://www.service-public.fr/abonnements/rss/actu-actualites-professionnels.rss","source_type":"rss","category":"entreprises-immobilier","authority":"official","crawl_policy":"rss-summary-only"}', '2026-07-28T00:36:01.362Z', '2026-07-28T00:36:01.362Z') ON CONFLICT(id) DO UPDATE SET name = excluded.name, url = excluded.url, source_type = excluded.source_type, category = excluded.category, authority = excluded.authority, crawl_policy = excluded.crawl_policy, active = 1, payload = excluded.payload, updated_at = excluded.updated_at;
INSERT INTO editorial_sources (id, name, url, source_type, category, authority, crawl_policy, active, payload, created_at, updated_at) VALUES ('acpr-actualites', 'ACPR Banque de France', 'https://acpr.banque-france.fr/fr/actualites', 'public-page', 'regulateur-assurance', 'regulator', 'public-title-and-summary', 1, '{"id":"acpr-actualites","name":"ACPR Banque de France","url":"https://acpr.banque-france.fr/fr/actualites","source_type":"public-page","category":"regulateur-assurance","authority":"regulator","crawl_policy":"public-title-and-summary"}', '2026-07-28T00:36:01.362Z', '2026-07-28T00:36:01.362Z') ON CONFLICT(id) DO UPDATE SET name = excluded.name, url = excluded.url, source_type = excluded.source_type, category = excluded.category, authority = excluded.authority, crawl_policy = excluded.crawl_policy, active = 1, payload = excluded.payload, updated_at = excluded.updated_at;
INSERT INTO editorial_sources (id, name, url, source_type, category, authority, crawl_policy, active, payload, created_at, updated_at) VALUES ('acpr-communiques', 'ACPR communiques', 'https://acpr.banque-france.fr/fr/communiques-de-presse', 'public-page', 'regulateur-assurance', 'regulator', 'public-title-and-summary', 1, '{"id":"acpr-communiques","name":"ACPR communiques","url":"https://acpr.banque-france.fr/fr/communiques-de-presse","source_type":"public-page","category":"regulateur-assurance","authority":"regulator","crawl_policy":"public-title-and-summary"}', '2026-07-28T00:36:01.362Z', '2026-07-28T00:36:01.362Z') ON CONFLICT(id) DO UPDATE SET name = excluded.name, url = excluded.url, source_type = excluded.source_type, category = excluded.category, authority = excluded.authority, crawl_policy = excluded.crawl_policy, active = 1, payload = excluded.payload, updated_at = excluded.updated_at;
INSERT INTO editorial_sources (id, name, url, source_type, category, authority, crawl_policy, active, payload, created_at, updated_at) VALUES ('legifrance', 'Legifrance', 'https://www.legifrance.gouv.fr/', 'reference', 'droit', 'official', 'reference-link-only', 1, '{"id":"legifrance","name":"Legifrance","url":"https://www.legifrance.gouv.fr/","source_type":"reference","category":"droit","authority":"official","crawl_policy":"reference-link-only"}', '2026-07-28T00:36:01.362Z', '2026-07-28T00:36:01.362Z') ON CONFLICT(id) DO UPDATE SET name = excluded.name, url = excluded.url, source_type = excluded.source_type, category = excluded.category, authority = excluded.authority, crawl_policy = excluded.crawl_policy, active = 1, payload = excluded.payload, updated_at = excluded.updated_at;
INSERT INTO editorial_watch_items (id, source_id, source_name, source_url, title, url, summary, relevance_score, topic, published_at, fetched_at, payload) VALUES ('watch-c9c4df305df4', 'service-public-particuliers', 'Service-Public.fr particuliers', 'https://www.service-public.fr/', 'Logement, copropriete et demarches: verifier les obligations avant travaux ou sinistre', 'https://www.service-public.fr/particuliers/vosdroits/N19808', 'Point de veille a transformer en checklist: documents, responsabilites et delais utiles pour syndics, bailleurs et coproprietaires.', 82, 'copropriete', '', '2026-07-28T00:36:01.331Z', '{"source_id":"service-public-particuliers","source_name":"Service-Public.fr particuliers","source_url":"https://www.service-public.fr/","title":"Logement, copropriete et demarches: verifier les obligations avant travaux ou sinistre","url":"https://www.service-public.fr/particuliers/vosdroits/N19808","summary":"Point de veille a transformer en checklist: documents, responsabilites et delais utiles pour syndics, bailleurs et coproprietaires.","topic":"copropriete","relevance_score":82,"fetched_at":"2026-07-28T00:36:01.331Z"}') ON CONFLICT(url) DO UPDATE SET title = excluded.title, summary = excluded.summary, relevance_score = excluded.relevance_score, topic = excluded.topic, published_at = excluded.published_at, fetched_at = excluded.fetched_at, payload = excluded.payload;
INSERT INTO editorial_watch_items (id, source_id, source_name, source_url, title, url, summary, relevance_score, topic, published_at, fetched_at, payload) VALUES ('watch-a5363540b8ca', 'acpr-actualites', 'ACPR Banque de France', 'https://acpr.banque-france.fr/fr/actualites', 'Veille assurance: rester attentif aux communications du regulateur', 'https://acpr.banque-france.fr/fr/actualites', 'Les communications du regulateur peuvent signaler des points de vigilance sur distribution, information client, contrats et pratiques du marche assurance.', 78, 'regulateur', '', '2026-07-28T00:36:01.334Z', '{"source_id":"acpr-actualites","source_name":"ACPR Banque de France","source_url":"https://acpr.banque-france.fr/fr/actualites","title":"Veille assurance: rester attentif aux communications du regulateur","url":"https://acpr.banque-france.fr/fr/actualites","summary":"Les communications du regulateur peuvent signaler des points de vigilance sur distribution, information client, contrats et pratiques du marche assurance.","topic":"regulateur","relevance_score":78,"fetched_at":"2026-07-28T00:36:01.334Z"}') ON CONFLICT(url) DO UPDATE SET title = excluded.title, summary = excluded.summary, relevance_score = excluded.relevance_score, topic = excluded.topic, published_at = excluded.published_at, fetched_at = excluded.fetched_at, payload = excluded.payload;
INSERT INTO editorial_watch_items (id, source_id, source_name, source_url, title, url, summary, relevance_score, topic, published_at, fetched_at, payload) VALUES ('watch-2da1d2167de3', 'legifrance', 'Legifrance', 'https://www.legifrance.gouv.fr/', 'Copropriete: suivre les textes applicables avant de publier un conseil juridique', 'https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000028779136/', 'Toute page sur l''obligation d''assurance copropriete doit rester prudente et renvoyer vers les textes publics lorsque le sujet est juridique.', 75, 'droit', '', '2026-07-28T00:36:01.334Z', '{"source_id":"legifrance","source_name":"Legifrance","source_url":"https://www.legifrance.gouv.fr/","title":"Copropriete: suivre les textes applicables avant de publier un conseil juridique","url":"https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000028779136/","summary":"Toute page sur l''obligation d''assurance copropriete doit rester prudente et renvoyer vers les textes publics lorsque le sujet est juridique.","topic":"droit","relevance_score":75,"fetched_at":"2026-07-28T00:36:01.334Z"}') ON CONFLICT(url) DO UPDATE SET title = excluded.title, summary = excluded.summary, relevance_score = excluded.relevance_score, topic = excluded.topic, published_at = excluded.published_at, fetched_at = excluded.fetched_at, payload = excluded.payload;
INSERT INTO newsletter_issues (id, slug, title, subject, summary, status, html_url, plain_text, payload, created_at, published_at, sent_at) VALUES ('issue-8ddcceb57b67', 'news/veille-assurance-immeuble-2026-07-28', 'Veille assurance immeuble: copropriete, contrats et devis', 'ImmeubleAssur - veille assurance immeuble 2026-07-28', 'Resume actionnable des signaux publics utiles aux syndics, bailleurs, SCI et coproprietaires non occupants.', 'published', '/news/veille-assurance-immeuble-2026-07-28', 'Veille assurance immeuble: copropriete, contrats et devis

Resume actionnable des signaux publics utiles aux syndics, bailleurs, SCI et coproprietaires non occupants.

La veille ImmeubleAssur transforme les signaux publics en actions de verification pour les immeubles, coproprietes, SCI et proprietaires non occupants.

Themes prioritaires cette semaine: copropriete, regulateur, droit.

Avant de demander un devis, relire le contrat actuel, l''appel de prime, les franchises, les exclusions et l''historique sinistres reste le meilleur levier de qualite.

Les actualites ne remplacent pas un audit contractuel: elles servent a declencher les bonnes questions et a preparer les documents utiles.

Le bon objectif n''est pas de publier du volume, mais de produire des pages qui aident vraiment un syndic, un bailleur ou une SCI a agir.

Actions:
- Verifier les contrats avant echeance reste prioritaire.
- Relier chaque actualite a une piece de dossier ou une clause a relire.
- Produire du contenu utile, source et oriente decision plutot que du volume SEO.
- Transformer les questions PNO/CNO, SCI et copropriete en demandes de devis qualifiees.

https://immeubleassur.com/news/veille-assurance-immeuble-2026-07-28', '{"issue":{"id":"issue-8ddcceb57b67","slug":"news/veille-assurance-immeuble-2026-07-28","title":"Veille assurance immeuble: copropriete, contrats et devis","subject":"ImmeubleAssur - veille assurance immeuble 2026-07-28","summary":"Resume actionnable des signaux publics utiles aux syndics, bailleurs, SCI et coproprietaires non occupants.","day":"2026-07-28","takeaways":["Verifier les contrats avant echeance reste prioritaire.","Relier chaque actualite a une piece de dossier ou une clause a relire.","Produire du contenu utile, source et oriente decision plutot que du volume SEO.","Transformer les questions PNO/CNO, SCI et copropriete en demandes de devis qualifiees."],"plain_text":"Veille assurance immeuble: copropriete, contrats et devis\n\nResume actionnable des signaux publics utiles aux syndics, bailleurs, SCI et coproprietaires non occupants.\n\nLa veille ImmeubleAssur transforme les signaux publics en actions de verification pour les immeubles, coproprietes, SCI et proprietaires non occupants.\n\nThemes prioritaires cette semaine: copropriete, regulateur, droit.\n\nAvant de demander un devis, relire le contrat actuel, l''appel de prime, les franchises, les exclusions et l''historique sinistres reste le meilleur levier de qualite.\n\nLes actualites ne remplacent pas un audit contractuel: elles servent a declencher les bonnes questions et a preparer les documents utiles.\n\nLe bon objectif n''est pas de publier du volume, mais de produire des pages qui aident vraiment un syndic, un bailleur ou une SCI a agir.\n\nActions:\n- Verifier les contrats avant echeance reste prioritaire.\n- Relier chaque actualite a une piece de dossier ou une clause a relire.\n- Produire du contenu utile, source et oriente decision plutot que du volume SEO.\n- Transformer les questions PNO/CNO, SCI et copropriete en demandes de devis qualifiees.\n\nhttps://immeubleassur.com/news/veille-assurance-immeuble-2026-07-28","html_url":"/news/veille-assurance-immeuble-2026-07-28","status":"published"},"synthesis_provider":"deterministic","synthesis_model":"local-template"}', '2026-07-28T00:36:01.362Z', '2026-07-28T00:36:01.362Z', NULL) ON CONFLICT(slug) DO UPDATE SET title = excluded.title, subject = excluded.subject, summary = excluded.summary, status = excluded.status, html_url = excluded.html_url, plain_text = excluded.plain_text, payload = excluded.payload, published_at = excluded.published_at;
INSERT OR REPLACE INTO ai_generation_runs (id, provider, model, task, status, input_hash, output_hash, payload, created_at) VALUES ('ai-95b377e24d9e', 'deterministic', 'local-template', 'editorial-synthesis', 'skipped', '76d4250539fb', 'df0b282142af', '{"error":"ai-disabled-or-missing-key","fetch_enabled":false,"ai_enabled":false}', '2026-07-28T00:36:01.362Z');
